# .github/workflows/main.yml
name: Call Reusable Maven Build Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  call-maven-build:
    uses: ./.github/workflows/maven-build-and-test.yml@main  # Replace with your own repo and branch
    with:
      java_version: '11'  # Pass Java version as input
    secrets:
      MY_SECRET_API_KEY: ${{ secrets.MY_SECRET_API_KEY }}  # Pass secret from the repository

