# .github/workflows/main.yml
name: Call Reusable Maven Build Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  call-maven-build:
    uses: ./.github/workflows/maven-build-and-test.yml
    with:
      java_version: "11" 
 
