name: Maven Build and Test

on:
  push:
    branches:
      - main  # Run the workflow when code is pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Run the workflow for pull requests targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu virtual machine for the build

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # Specify the Java version
        distribution: 'temurin'  # Choose the JDK distribution

    # Step 3: Cache Maven dependencies
    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build and test the project
    - name: Build with Maven
      run: mvn clean install

    # Step 5: Run unit tests
    - name: Run Tests
      run: mvn test
