# .github/workflows/maven-build-and-test.yml
name: Maven Build and Test Workflow

on:
  workflow_call:  # Specifies that this workflow is callable by another workflow
    inputs:
      java_version:
        description: 'Java version to use'
        required: true
        default: '11'
        type: string  # Define the type for the input
    secrets: {}  # If you don't need secrets, this can be an empty object

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java_version }}
          distribution: temurin

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Step 4: Build and run tests
      - name: Build with Maven
        run: mvn clean package

    
